routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KariawanController;
use App\Http\Controllers\PaymentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('kariawan/index');})->name('home');


Route::resource('kariawan',KariawanController::class);
Route::get('kariawan',[KariawanController::class,'datakariawan'])->name('data-ajax');
Route::post('payment-send',[PaymentController::class,'sendPayment'])->name('send-payment');
Route::get('product',[PaymentController::class,'index'])->name('product');
Route::get('payment/{id}',[PaymentController::class,'Buyproduct'])->name('payment');

app/Models/Kariawan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kariawan extends Model
{
    use HasFactory;
    protected $table = 'karyawans';
    protected $fillable = [ 'id','name', 'pekerjaan','created_at'];
    public $incrementing = false;
}

app/Http/Controllers/KariawanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;
use App\Models\Kariawan;
use Datatables;
use DB;
use Carbon;

class KariawanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('kariawan/index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kariawan/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
        $input = $request->all();
        DB::beginTransaction();
        try {
            $uuid = Uuid::uuid1();
            $input['id'] = $uuid;
            // dd($uuid);
            Kariawan::create($input);
            DB::commit();
            return redirect()->route('home')
            ->with('success','Karyawan data successfully');
        } catch (Exception $e) {
            DB::rollBack();
            return back()->with('error', 'Terjadi Kesalan Silahkan Coba Lagi Nanti');
        }
       

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $karyawan = Kariawan::find($id);
        return view('kariawan/edit',compact('karyawan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $kariawan = kariawan::find($id);
        DB::beginTransaction();
        try {
            $uuid = Uuid::uuid1();
            $update['name'] = $input['name'];
            $update['pekerjaan'] = $input['pekerjaan'];
            $kariawan->update($update);
            DB::commit();
            return redirect(route('home'))->with('success', 'Kariawan berhasil di update');
        } catch (Exception $e) {
            DB::rollBack();
            return back()->with('error', 'Terjadi Kesalan Silahkan Coba Lagi Nanti');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $karyawan = Kariawan::where('id',$id)->firstOrFail();
        $karyawan->delete();
        return redirect()->route('home')
         ->with('success','Karyawan deleted successfully');
    }



    public function datakariawan(Request $request)
    {
        if(request()->ajax()) {
            $data = Kariawan::select('id','name','pekerjaan','created_at')->get();
            return Datatables()->of($data)
            ->addColumn('tanggal',function($row){
                $dt = \Carbon\Carbon::parse($row->created_at)->isoFormat('dddd');
                $dat = \Carbon\Carbon::parse($row->created_at)->format('d');
                $tanggal_minggu = ($dt == "Sunday") ? "hari Minggu" : "";
                $tanggal_biasa = ($dat % 2 == 0) ? "Genap" : "Ganjil";
                return \Carbon\Carbon::parse($row->created_at)->format('d M Y') .'<span class="badge badge-secondary">'.$tanggal_biasa ." " .$tanggal_minggu.'</span>';

            }) 
            ->addColumn('action',function($row){
                $btn = '<div class="btn-group" role="group" aria-label="Basic example">
                <a href="' . route("kariawan.edit", $row->id) . '" class="edit btn btn-warning btn-sm">Edit</a>
            
                <form action="' . route("kariawan.destroy", $row->id) . '" class="form-process-order form-process-hapus-' . $row->id . '" method="POST">
                '.csrf_field().'
                '.method_field('DELETE').'
                <button type="submit" class="btn btn-danger btn-sm process" data-process="process" data-hapus="'.$row->id.'">Delete</button>
            </form>
                </div>';
                 return $btn;
            })
            ->rawColumns(['action','tanggal'])
            ->addIndexColumn()
            ->make(true);
        }
    }
}

resources/views/kariawan/create.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Ipaymu</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
</head>
<body>
  
    <div class="container">
        <div class="flex justify-center pt-8 sm:justify-start sm:pt-0">
        <center> <img width="20%" src="https://3.bp.blogspot.com/-8-OzIAEbSCA/XpezSSZw9oI/AAAAAAAASxg/IsOqbHtucWc4OnZEKxEvK3cvp_o_rVfRACLcBGAsYHQ/s1600/Nomor-Call-Center-Customer-Service-iPaymu.jpg" alt="" srcset="">
</center><hr>     
    </div>
        <form action="{{ route('kariawan.store') }}" method="post">
            @csrf
            
            <div class="form-group">
                <label>Name:</label>
                <input type="text" name="name" class="form-control" placeholder="Name" required="">
            </div>
  
            <div class="form-group">
                <label>Pekerjaan:</label>
                <input type="text" name="pekerjaan" class="form-control" placeholder="Pekerjaan" required="">
            </div>
   
   
            <div class="form-group">
                <button class="btn btn-success btn-submit">Simpan</button>
            </div>
  
        </form>
    </div>
  
</body>

   
</html>

resources/views/kariawan/edit.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Ipaymu</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
</head>
<body>
  
    <div class="container">
        <div class="flex justify-center pt-8 sm:justify-start sm:pt-0">
           <center> <img width="20%" src="https://3.bp.blogspot.com/-8-OzIAEbSCA/XpezSSZw9oI/AAAAAAAASxg/IsOqbHtucWc4OnZEKxEvK3cvp_o_rVfRACLcBGAsYHQ/s1600/Nomor-Call-Center-Customer-Service-iPaymu.jpg" alt="" srcset="">
</center><hr>

        </div>
        <form action="{{ route('kariawan.update',$karyawan->id) }}" method="post">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label>Name:</label>
                <input type="text" name="name" class="form-control" value="{{ $karyawan->name }}" placeholder="Name" required="">
            </div>
  
            <div class="form-group">
                <label>Pekerjaan:</label>
                <input type="text" name="pekerjaan" class="form-control"  value="{{ $karyawan->pekerjaan }}"  placeholder="Pekerjaan" required="">
            </div>
   
   
            <div class="form-group">
                <button class="btn btn-success btn-submit">Update</button>
            </div>
  
        </form>
    </div>
  
</body>

   
</html>